---
openapi: "3.0.3"

info:
  title: "OpenAPI Hello World"
  version: "0.1.0"

paths:
  "/helloworld":
    get:
      responses:
        "200":
          description: "sample"
          content:
            application/json:
              schema:
                type: object
                required:
                  - example
                properties:
                  example:
                    type: string
              example:
                example: "Hello World!"
  "/basicauth":
    get:
      security:
        - basicAuth: []
      responses:
        "200":
          description: "basic auth"
          content:
            application/json:
              schema:
                type: object
                required:
                  - example
                properties:
                  example:
                    type: string
              example:
                example: "ok"

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
