---
name: GitHub Actions Hello World!

on:
  workflow_dispatch:

jobs:
  build:
    name: echo
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run actionlint
        shell: bash
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
